spring:
  datasource:
    url: jdbc:mysql://localhost:5440/new_user_service_api
    username: newuserservice
    password: newpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  liquibase:
    enabled: false
  security :
    jwt-secret-key : bXkgc2VjcmV0IGtleSBmb3IgdXNlciByZWdpc3RyYXRpb24gd2l0aCBzZWN1cml0eQ==
