spring:
  datasource:
    url: jdbc:mysql://localhost:5438/user_service_api_design
    username: user_service_api_design
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  liquibase:
    enabled: true